# Generated by Django 5.0.7 on 2024-08-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbackend', '0003_alter_goods_good_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='good_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/%Y/%m'),
        ),
    ]
