# Generated by Django 5.0.7 on 2024-08-22 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbackend', '0004_alter_goods_good_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='created_by',
        ),
    ]
