# Generated by Django 5.0.7 on 2024-08-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbackend', '0006_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=100)),
                ('good_price', models.FloatField()),
                ('good_image', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/%Y/%m')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
