# Generated by Django 5.0.7 on 2024-09-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbackend', '0009_cart_user_history_user_orders_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
