# Generated by Django 5.0.7 on 2024-09-13 04:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercart',
            name='good_description',
            field=models.CharField(default='No description available', max_length=100),
        ),
        migrations.AddField(
            model_name='usercart',
            name='good_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/%Y/%m'),
        ),
        migrations.AddField(
            model_name='usercart',
            name='good_name',
            field=models.CharField(default='No description available', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercart',
            name='good_price',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
