# Generated by Django 5.0.7 on 2024-09-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusers', '0002_usercart_created_at_usercart_good_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='goods',
        ),
        migrations.AddField(
            model_name='usercart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='UserCartItem',
        ),
    ]
