# Generated by Django 5.0.7 on 2024-09-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusers', '0003_remove_usercart_goods_usercart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='good_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/uesrcart/%Y/%m'),
        ),
    ]
