# Generated by Django 5.0.7 on 2024-09-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusers', '0004_alter_usercart_good_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='good_image',
            field=models.ImageField(blank=True, default='images/default1.jpg', null=True, upload_to='images/uesrcart/%Y/%m'),
        ),
    ]
