# Generated by Django 5.0.7 on 2024-09-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusers', '0005_alter_usercart_good_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
