# Generated by Django 5.0.7 on 2024-08-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfdemo', '0003_alter_student_age_alter_student_class_null_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publish',
        ),
    ]
