# Generated by Django 5.0.7 on 2024-08-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_department_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='role',
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
